### ISSUE TITLE
No resource found that matches the given name (at 'resource' with value '@xml/nfc_tech_filter')

### ISSUE THREAD

**Issue by KBepo** [Lube/nfc-react-native#13]
Hello,

I've been following instructions and even used example to include this into my project but i keep getting this error:

No resource found that matches the given name (at 'resource' with value '@xml/nfc_tech_filter')

I've made a new folder named xml inside res folder and I've placed nfc_tech_filter.xml from instructions. But can't make it work. What did I miss?

**Comment by smitch88** [comment]
I did as the directions stated and it worked for me.

In res/xml
```
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2">
  <tech-list>
    <tech>android.nfc.tech.MifareClassic</tech>
  </tech-list>
</resources>
```
In manifest <activity>
```
<intent-filter>
  <action android:name="android.nfc.action.TECH_DISCOVERED"/>
  </intent-filter>

  <meta-data android:name="android.nfc.action.TECH_DISCOVERED"
    android:resource="@xml/nfc_tech_filter" />
```

In manifest outside application
```
<uses-permission android:name="android.permission.NFC" />
<uses-permission android:name="android.permission.INTERNET" />
```

**Comment by Mimble-Wimble** [comment]
@smitch88 What did you name the .xml file in `app/src/main/res/`? I titled mine `nfc_tech_filter.xml` as KBepo did and I'm getting the same error.

**Comment by smitch88** [comment]
@Mimble-Wimble I think you are missing .../xml perhaps. Here is where I have it,

<img width="257" alt="screen shot 2017-07-16 at 10 59 36 am" src="https://user-images.githubusercontent.com/762107/28248656-f1547702-6a15-11e7-9930-0029aa6bd892.png">

I also only target a specific set of tag types  as an `OR` by doing something like...if you list them out in a single `tech-list` it will assume its an `AND` so unless your tag can identify as all the types it would not work.

<img width="690" alt="screen shot 2017-07-16 at 11 00 24 am" src="https://user-images.githubusercontent.com/762107/28248662-10c0c384-6a16-11e7-8557-f43be1d0759f.png">

**Comment by Mimble-Wimble** [comment]
@smitch88 Thanks for this! That's exactly what was needed. Adding the `xml/` directory and placing `nfc_tech_filter.xml` in there resolved the previous error.

**Comment by henrikra** [comment]
@Mimble-Wimble @KBepo So this can be closed?

**Comment by Mimble-Wimble** [comment]
@henrikra Yep. All good here.
