### ISSUE TITLE
(0 , _nfcReactNative2.default) is not a function error

### ISSUE THREAD

**Issue by mattb2401** [Lube/nfc-react-native#4]
Constantly getting 
`(0 , _nfcReactNative2.default) is not a function` error

**Comment by lube** [comment]
Try the version released las week.

**Comment by mariomka** [comment]
Same error here in the last version (0.4.4) on call getTagId()

```
undefined is not a function (evaluating '(0,_nfcReactNative2.default)()')
```

**Comment by lube** [comment]
Did you try the sample project?

**Comment by mariomka** [comment]
I'm sorry, the sample project works fine. I did some wrong.

Thank you.

**Comment by lube** [comment]
No worries good luck with your project!
