### ISSUE TITLE
Despite this being explicitly for Android only, will this ever become iOS compatible?

### ISSUE THREAD

**Issue by julesmoretti** [Lube/nfc-react-native#6]
I am currently looking into NFC technology for an iOS app and am creating those app's using react-native. I was wondering if this module will ever have some sort of iOS compatibility?

Thank you for your time and contributions!

**Comment by lube** [comment]
AFAIK Apple doesn't have plans to support custom nfc integration (only with apple pay). If they decide to move forward I'll probably take a stab at it.

**Comment by MichaelFBA** [comment]
@Lube It looks like ios will support it core NFC its called
